@startuml

skinparam {
    defaultFontColor #4080a9
    defaultBackgroundColor #d7f8ff
    defaultComponentColour #61d9de
    defaultActorColour #61d9de
    defaultFontSize 16
    defaultArrowThickness 6
    actorStyle awesome
    linetype polyline
}

rectangle Organisations {
    component "API Provider"  as AG
    component "API Consumer" as AC
    actor "Application Developer" as APPD
    actor "API Developer" as APID
}
rectangle Hira {
    component "Developer Portal" as DP
    component "Connector Plane" as CP
    component "API Provider"  as HAP
    'DP -[hidden]- CP
    'HAP -[hidden]- CP
}
rectangle "Health Sector Participants" as HSP {
    actor "Health Consumer" as HC
    actor "Whanau"
    actor "Iwi"

}
rectangle "Health Workforce"  as HWF {
    actor "Health Worker" AS HW
}

'HSP --[hidden]up-- HWF
'Organisations --[hidden]up-- Hira

@enduml